#!/bin/bash

LANGUAGE=$(grep '^lang:' /etc/tech-scripts/choose.conf | cut -d' ' -f2)

if [[ "$LANGUAGE" == "Русский" ]]; then
    MSG_NO_SCRIPTS="Нет доступных скриптов или директорий!"
    MSG_CANCELLED="Выбор отменен!"
    MSG_BACK="назад"
    MSG_SELECT="Выберите опцию"
    MSG_CD_ERROR="Ошибка: Не удалось перейти в директорию!"
    DIRECTORY_FORMAT="директория"
    SCRIPT_FORMAT="скрипт"
    OPTION_FORMAT="опция"
    CONFIG_FORAMT="конфиг"
    
    QM_NOT_FOUND="Утилита qm не найдена. Убедитесь, что Proxmox установлен!"
    NO_VMS="Нет доступных виртуальных машин!"
    SELECT_VM="Выберите виртуальную машину"
    SELECT_ACTION="Выберите действие"
    MSG_CONFIRM_DELETE="Вы уверены, что хотите удалить"
    MSG_ERROR="Ошибка"
    CONTINUE_VM="Продолжить работу с текущей виртуальной машиной?"

    PCT_NOT_FOUND="Утилита pct не найдена. Убедитесь, что Proxmox установлен!"
    NO_CONTAINERS_LXC="Нет доступных LXC-контейнеров!"
    SELECT_CONTAINER="Выберите контейнер"
    CONTINUE_LXC="Продолжить работу с текущим контейнером?"

    TITLE_DANGER="Подтверждение удаления"
    MESSAGE_DANGER="Вы точно хотите удалить все файлы tech-scripts?"
    YES="Да"
    NO="Нет"
    DELETING="Удаление файлов..."
    DELETED="Файлы успешно удалены!"

    TITLE_EDITOR="Выбор текстового редактора"
    MSG_EDITOR="Выберите текстовый редактор:"
    TITLE_CUSTOM_EDITOR="Пользовательский редактор"
    MSG_CUSTOM_EDITOR="Введите команду вашего текстового редактора:"
    MSG_INVALID_EDITOR="Неверный выбор!"
    MSG_SUCCESS_EDITOR="Текстовый редактор установлен:"

    CPU_TEST_TITLE="Стресс-тест процессора"
    CPU_TEST_QUESTION="Вы хотите выполнить стресс-тест процессора?"
    PROGRESS_TITLE="Прогресс выполнения"
    INSTALL_TITLE="Установка необходимых компонентов"
    INSTALL_QUESTION="sysbench не установлен. Хотите установить его?"
    PACKAGE_MANAGER_ERROR="Не удалось определить пакетный менеджер. Установите sysbench вручную!"
    
    MEMORY_TEST_TITLE="Стресс-тест памяти"
    MEMORY_TEST_QUESTION="Вы хотите выполнить стресс-тест памяти?"
    
    MSG_SELECT_DISK="Выберите директорию"
    MSG_SPEED_WRITE_DISK="Скорость записи:"
    MSG_SPEED_READ_DISK="Скорость чтения:"
    MSG_TIME_WRITE_DISK="Время записи:"
    MSG_TIME_READ_DISK="Время чтения:"
    MSG_FAILED_DISK="Не удалось измерить скорость"
    MSG_SELECTED_DIR_DISK="Выбранная директория:"
    MSG_NO_MOUNTS_DISK="Нет доступных точек монтирования!"

    TITLE_AUTOUPDATE="Обновление системы"
    QUESTION_AUTOUPDATE="Вы хотите запустить обновление системы?"
    UPDATING_AUTOUPDATE="Обновление системы..."
    COMPLETE_AUTOUPDATE="Обновление завершено!"
    ERROR_AUTOUPDATE="Пакетный менеджер не найден. Обновление отменено!"

    CONTINUE_CONFIG="Вы хотите продолжить?"

    ERROR_MSG_NUMBER_GRUB="Введите количество секунд для задержки перед запуском:"
    CONFIRM_PROMPT_GRUB="Вы ввели: %s секунд. Это правильно?"
    ERROR_MSG_GRUB="Ошибка: Введите целое число."
    SUCCESS_MSG_GRUB="Задержка перед запуском установлена на %s секунд. Конфигурация GRUB обновлена!"
    JQ_NOT_FOUND_SSH="Не удалось определить пакетный менеджер. Установите jq вручную!"
    SCRIPT_UPDATE_SSH="Обновление скрипта"
    REMOVE_SSH="Удаление"
    REMOVE_ALL_SSH="Хотите удалить конфигурацию, скрипт и сервис ssh.alert?"
    CREATE_NOTIFY_SSH="Создание оповещения"
    INSTALL_JQ_SSH="Установка jq..."
    BOT_TOKEN_SSH="Введите токен вашего Telegram-бота: "
    CHAT_ID_SSH="Введите ваш chat_id в Telegram: "
    CREATE_SCRIPT_SSH="Создание скрипта в $SCRIPT_DIR_SSH/alert.sh..."
    ADD_AUTOSTART_SSH="Добавление в автозапуск..."
    SUCCESS_INSTALL_SSH="Скрипт успешно установлен и добавлен в автозапуск!"
    SCRIPT_LOCATION_SSH="Скрипт расположен в: $SCRIPT_DIR_SSH/alert.sh"
    SERVICE_LOCATION_SSH="Сервис скрипта расположен в: /etc/systemd/system/ssh.alert.service"
    CONFIG_LOCATION_SSH="Конфиг скрипта расположен в: $CONFIG_FILE_SSH"
    ALREADY_INSTALLED_SSH="Скрипт уже установлен и запущен!"
    REMOVE_CHOICE_SSH="Хотите удалить ssh.alert из автозапуска?"
    REMOVED_SSH="ssh.alert удален из автозапуска!"
    START_CHOICE_SSH="Скрипт уже установлен. Хотите запустить его сейчас?"
    STARTED_SSH="Скрипт запущен!"
    NOT_STARTED_SSH="Скрипт не запущен!"
    SERVICE_MISSING_SSH="Скрипт уже установлен, но сервис ssh.alert.service не найден!"
    CREATE_CHOICE_SSH="Хотите создать и запустить сервис?"
    SERVICE_CREATED_SSH="Сервис создан и запущен!"
    REMOVE_CONFIG_SSH="Хотите удалить конфигурационный файл $CONFIG_FILE_SSH?"
    REMOVE_SCRIPT_SSH="Хотите удалить скрипт $SCRIPT_DIR_SSH/alert.sh?"
    UPDATE_SCRIPT_SSH="Вы хотите обновить скрипт?"
    UPDATE_SUCCESS_SSH="Скрипт успешно обновлен!"
    CREATE_ALERT_SSH="Хотите ли вы создать оповещение о входах по SSH через Telegram?"
    CONFIG_EXISTS_SSH="Конфигурационный файл уже существует. Пропускаем создание!"
    TEST_MESSAGE_SSH="✅ Вы успешно настроили систему оповещений о входах по SSH ✅"
    TEST_FAILED_SSH="Не удалось отправить тестовое сообщение. Проверьте токен и chat_id!"
    SUPER_GROUP_ID_SSH="Введите ID цепочки сообщений (необязательно):"
    PROHIBIT_SOUND_SSH="Отправлять без звука?" "Хотите отправлять сообщения без звука?"
    PROHIBIT_FORWARDING_SSH="Запретить пересылку?" "Хотите запретить пересылку сообщений?"
    CONFIG_REMOVE_SSH="Конфиг удален:"
    SCRIPT_REMOVE_SSH="Скрипт удален:"
    SERVICE_REMOVE_SSH="Сервис удален:"
    FAILED_SSH="🚨 Неудачная попытка входа 🚨"
    SUCCESS_SSH="✅ Успешный вход ✅"
    CLOSED_SSH="❌ Отмененная попытка входа ❌"
    ERROR_SSH="Ошибка при отправке сообщения"
    SENT_SSH="Сообщение успешно отправлено."
else
    MSG_NO_SCRIPTS="No available scripts or directories!"
    MSG_CANCELLED="Selection cancelled!"
    MSG_BACK="back"
    MSG_SELECT="Select an option"
    MSG_CD_ERROR="Error: Failed to change directory!"
    DIRECTORY_FORMAT="directory"
    SCRIPT_FORMAT="script"
    OPTION_FORMAT="option"
    CONFIG_FORAMT="config"

    QM_NOT_FOUND="Utility qm not found. Make sure Proxmox is installed!"
    NO_VMS="No available virtual machines!"
    SELECT_VM="Select virtual machine"
    SELECT_ACTION="Select action"
    MSG_CONFIRM_DELETE="Are you sure you want to delete"
    MSG_ERROR="Error"
    CONTINUE_VM="Continue working with the current virtual machine?"

    PCT_NOT_FOUND="Utility pct not found. Make sure Proxmox is installed!"
    NO_CONTAINERS_LXC="No available LXC containers!"
    SELECT_CONTAINER="Select container"
    CONTINUE_LXC="Continue working with the current container?"

    TITLE_DANGER="Delete Confirmation"
    MESSAGE_DANGER="Are you sure you want to delete all tech-scripts files?"
    YES="Yes"
    NO="No"
    DELETING="Deleting files..."
    DELETED="Files deleted successfully!"

    TITLE_EDITOR="Text Editor Selection"
    MSG_EDITOR="Choose your text editor:"
    TITLE_CUSTOM_EDITOR="Custom Editor"
    MSG_CUSTOM_EDITOR="Enter the command custom text editor:"
    MSG_INVALID_EDITOR="Invalid choice!"
    MSG_SUCCESS_EDITOR="Text editor set to:"

    CPU_TEST_TITLE="CPU Stress Test"
    CPU_TEST_QUESTION="Do you want to perform a CPU stress test?"
    PROGRESS_TITLE="Progress"
    INSTALL_TITLE="Installing Required Components"
    INSTALL_QUESTION="sysbench is not installed. Do you want to install it?"
    PACKAGE_MANAGER_ERROR="Failed to detect package manager. Please install sysbench manually!"
    
    MEMORY_TEST_TITLE="Memory stress test"
    MEMORY_TEST_QUESTION="Do you want to perform a memory stress test?"
    
    MSG_SELECT_DISK="Select directory"
    MSG_SPEED_WRITE_DISK="Write speed:"
    MSG_SPEED_READ_DISK="Read speed:"
    MSG_TIME_WRITE_DISK="Write time:"
    MSG_TIME_READ_DISK="Read time:"
    MSG_FAILED_DISK="Failed to measure speed"
    MSG_SELECTED_DIR_DISK="Selected directory:"
    MSG_NO_MOUNTS_DISK="No available mount points!"

    TITLE_AUTOUPDATE="System Update"
    QUESTION_AUTOUPDATE="Do you want to start the system update?"
    UPDATING_AUTOUPDATE="Updating the system..."
    COMPLETE_AUTOUPDATE="Update completed!"
    ERROR_AUTOUPDATE="The package manager was not found. The update has been canceled!"

    CONTINUE_CONFIG="Do you want to continue?"

    ERROR_MSG_NUMBER_GRUB="Enter the number of seconds for the boot delay:"
    CONFIRM_PROMPT_GRUB="You entered: %s seconds. Is this correct?"
    ERROR_MSG_GRUB="Error: Please enter a whole number."
    SUCCESS_MSG_GRUB="Boot delay set to %s seconds. GRUB configuration updated!"
    JQ_NOT_FOUND_SSH="Failed to detect package manager. Install jq manually!"
    SCRIPT_UPDATE_SSH="Script update"
    REMOVE_SSH="Removal"
    REMOVE_ALL_SSH="Do you want to remove the configuration, script, and ssh.alert service?"
    CREATE_NOTIFY_SSH="Creating notification"
    INSTALL_JQ_SSH="Installing jq..."
    BOT_TOKEN_SSH="Enter your Telegram bot token: "
    CHAT_ID_SSH="Enter your Telegram chat_id: "
    CREATE_SCRIPT_SSH="Creating script in $SCRIPT_DIR_SSH/alert.sh..."
    ADD_AUTOSTART_SSH="Adding to autostart..."
    SUCCESS_INSTALL_SSH="Script successfully installed and added to autostart!"
    SCRIPT_LOCATION_SSH="The script is located in: $SCRIPT_DIR_SSH/alert.sh"
    SERVICE_LOCATION_SSH="The script service is located in: /etc/systemd/system/ssh.alert.service"
    CONFIG_LOCATION_SSH="The script config is located in: $CONFIG_FILE_SSH"
    ALREADY_INSTALLED_SSH="Script is already installed and running!"
    REMOVE_CHOICE_SSH="Do you want to remove ssh.alert from autostart?"
    REMOVED_SSH="ssh.alert removed from autostart!"
    START_CHOICE_SSH="Script is already installed. Do you want to start it now?"
    STARTED_SSH="Script started!"
    NOT_STARTED_SSH="Script not started!"
    SERVICE_MISSING_SSH="Script is already installed, but ssh.alert.service is missing!"
    CREATE_CHOICE_SSH="Do you want to create and start the service?"
    SERVICE_CREATED_SSH="Service created and started!"
    REMOVE_CONFIG_SSH="Do you want to remove the configuration file $CONFIG_FILE_SSH?"
    REMOVE_SCRIPT_SSH="Do you want to remove the script $SCRIPT_DIR_SSH/alert.sh?"
    UPDATE_SCRIPT_SSH="Do you want to update the script?"
    UPDATE_SUCCESS_SSH="Script successfully updated!"
    CREATE_ALERT_SSH="Do you want to create an SSH login alert via Telegram?"
    CONFIG_EXISTS_SSH="Configuration file already exists. Skipping creation!"
    TEST_MESSAGE_SSH="✅ You have successfully set up an SSH login notification system ✅"
    TEST_FAILED_SSH="Failed to send test message. Please check your token and chat_id!"
    SUPER_GROUP_ID_SSH="Enter the message thread ID (optional):"
    PROHIBIT_SOUND_SSH="Send silently?" "Do you want to send messages without sound?"
    PROHIBIT_FORWARDING_SSH="Protect content?" "Do you want to protect message content from forwarding?"
    CONFIG_REMOVE_SSH="Config removed:"
    SCRIPT_REMOVE_SSH="Script removed:"
    SERVICE_REMOVE_SSH="Service removed:"
    FAILED_SSH="🚨 Failed login attempt 🚨"
    SUCCESS_SSH="✅ Successful login ✅"
    CLOSED_SSH="❌ Cancelled login attempt ❌"
    ERROR_SSH="Error sending message"
    SENT_SSH="Message sent successfully."
fi
